List<String> comment = [
  "Wow, that's amazing!",
  "You nailed it!",
  "Great job!",
  "Superb!",
  "Awesome work!",
  "You're incredible!",
  "Fantastic!",
  "Well done!",
  "Impressive stuff!",
  "You're a star!",
  "Bravo!",
  "Outstanding!",
  "So good!",
  "Phenomenal!",
  "Incredible talent!",
  "Perfect!",
  "Mind-blowing!",
  "Exceptional!",
  "Top-notch!",
  "Keep shining!",
];

List<String> reply = [
  "Pleasure!",
  "Welcome!",
  "Delighted!",
  "Gladly!",
  "Cheers!",
  "Sure!",
  "Happy!",
  "Appreciated!",
  "Grateful!",
  "Indeed!",
  "Absolutely!",
  "Honored!",
  "Ecstatic!",
  "Thrilled!",
  "Blessed!",
  "Joyful!",
  "Heartfelt!",
  "Thankful!",
  "Excited!",
  "Overjoyed!",
];
